Repository rakenduste-programmeerimine-2023/learner, pull requests merged in 2023-11, with the labels that each got.

#1 docs: update README with project information
  README.md
  wireframe.png
Labels: documentation

#12 Cleared frontpage
  app/page.tsx
Labels: frontend

#14 style: update navbar styling to use MUI components, closes #4
  app/layout.tsx
  package-lock.json
  package.json
Labels: design

#20 issue-19: add create btn dynamic, closes #19
  app/layout.tsx
Labels: frontend

#18 issue-8: login/out, signup, closes #8
  app/createForm/page.tsx
  app/layout.tsx
  app/page.tsx
  app/profile/page.tsx
Labels: frontend

#31 feat(api): fetch external API to main page, closes #15
  app/page.tsx
  components/InspirationalQuote.tsx
Labels: frontend

#33 refactor(api): display external API if user is signed out, closes #32
  app/page.tsx
  components/InspirationalQuote.tsx
Labels: bug, frontend, design

#36 feat: add sample data to each table, closes #27
  supabase/migrations/20231116121936_form.sql
  supabase/seed.sql
Labels: backend

#49 feat: add UI for reading and navigating questions, closes #43
  app/form/page.tsx
  components/ViewQuestion.jsx
  components/ViewQuestion.tsx
  tsconfig.json
Labels: frontend, backend
